### ISSUE TITLE
Develop YAML Data Management Mechanism

### ISSUE THREAD

**Issue by jsedlak** [jsedlak/reach#25]
A number of scenarios that would benefit from Content As Code arise when developing with a headless CMS. One primary reason is when developing multiple sites for a single customer that are spread between Hubs and/or Organizations. Another scenario is when you want to productize components into a reusable library of Content+Code.

To support this scenario, I plan on supporting a platform for uploading and processing YAML files that can represent any number of the various data stored within Reach. I am not going to close the door on formats other than YAML, such as JSON, but will focus on YAML for its cleanliness and simplicity.

An example of how this might work is pictured below. An API endpoint will be made available to upload a YAML file to an organization and hub. The API will store the data in a pluggable blob storage, such as Azure Blob Storage, to be made available to the underlying process. The API will then kick off a long running process on an "ETL Grain", that will utilize a common "ETL Engine" framework and underlying parser.

![Image](https://github.com/user-attachments/assets/223fed04-f420-4482-bfa3-57f58c488ccc)

The dependency on a Reach CLI is not a requirement, but will make use far easier, since developers will likely need to make frequent requests to get or push YAML files.

Building a pluggable architecture for formatting will become useful to support import/export of YAML and any other format that developers wish to or need to develop.

The ETL Engine should maintain a "working model" of any parsed document. Ideally this comes as a tree of commands that represent the YAML, such that there is no further duplication of existing models.

For example, consider the following YAML

```yaml
editorDefinitions:
  - textbox:
      displayName: TextBox
      parameters:
        - Required:
            displayName: Required
            type: Boolean
        - MaxLength:
            - displayName: Max Length
            - type: Number
fieldDefinitions:
  - single-line-text:
      displayName: Single Line Text
      definition: textbox
      parameters:
        - MaxLength
```

This could be modeled as followed

![Image](https://github.com/user-attachments/assets/85512bce-308b-4cc6-b2c7-85761c933bcb)

This will need a supporting framework, something that will look like

```csharp
public class ParsedNode 
{
    public string Name { get; set; }

    public IEnumerable<AggregateCommand> Commands { get; set; } = [];

    public IEnumerable<ParsedNode> Children { get; set; } = [];
}
```
